### PR TITLE
Added code analyzers and fixed locale issues.

### LINKED ISSUE #154: float.Parse() fails sometimes when the computer language isn't English
In Parser.cs line, 861:

`value = new Value(float.Parse(t.value as String));`

When a playtester tried my game on a computer with a French Canadian keyboard, the dialogue would crash.

I think it needs to be changed to this:
`value = new Value(float.Parse(t.value as String, System.Globalization.CultureInfo.InvariantCulture));`

### PR DESCRIPTION
**Pull request by Tamschi**
Fixes #154.

All program parsing and output should now use `InvariantCulture` or `StringComparison.Invariant`.

Currently, the output for logging etc. uses `CurrentCulture` instead of `InvariantCulture`.  
This is the same behaviour as before, but now explicit to mark those places as not processed. However, it may be better to set these to English or Invariant too, since the error messages aren't localised.

-----

I added the FxCop Analyzers to the project to find the locale problems, so warnings for certain issues should now show up when building with the Roslyn infrastructure. This happens with Visual Studio for example, but please check that I didn't break anything for your workflow.

I did some tiny fixes where suppressing the warning would have been more effort, but there are many warnings I just suppressed for now. I'll mark them in the commit via comment where appropriate, if that's supported here.

### CODE REVIEW

File: YarnSpinner/YarnSpinnerLexer.cs [hunk 1]
```diff
@@ -52,9 +52,18 @@ public const int
...
+
+    public const int Title = 1;
+    public const int Tags = 2;
+    public const int HeaderText = 3;
+    public const int Body = 4;
+    new public const int Text = 5;
+    public const int Shortcuts = 6;
+    public const int Command = 7;
+    new public const int Action = 8;
+    public const int Option =9;
```
Comment (Tamschi) [inline YarnSpinner/YarnSpinnerLexer.cs]:
```suggestion
    public const int Option = 9;
```
Forgot to add a space here, so I'm trying out the suggestion system...

File: YarnSpinner/YarnSpinnerLexer.cs [hunk 2]
```diff
@@ -52,9 +52,18 @@ public const int
...
 		OPTION_LINK=75;
-	public const int
-		Title=1, Tags=2, HeaderText=3, Body=4, Text=5, Shortcuts=6, Command=7, 
-		Action=8, Option=9, OptionLink=10;
+
+    public const int Title = 1;
+    public const int Tags = 2;
+    public const int HeaderText = 3;
+    public const int Body = 4;
+    new public const int Text = 5;
```
Comment (Tamschi) [inline YarnSpinner/YarnSpinnerLexer.cs]: This constant hides a base member and it would probably be a bad idea to suppress that warning in general.  
Having the hiding marked explicitly here is in my opinion worth breaking up the formatting. (I'd personally break this up into an enum, but that's definitely out of scope here and I don't want to be prescriptive regarding style.)

File: YarnSpinnerConsole/Main.cs [hunk 3]
```diff
@@ -420,7 +425,8 @@ static internal Dialogue CreateDialogue(ExecutionOptions options, ConsoleRunnerI
                     {
                         dialogue.LogErrorMessage("ASSERTION FAILED: " + parameters[1].AsString);
                     }
-                    else {
+                    else
+                    {
```
Comment (Tamschi) [inline YarnSpinnerConsole/Main.cs]: I accidentally hit auto-format in this file. (Sorry.)  
Is this alright or should I apply a specific formatting style?

File: YarnSpinnerConsole/ProgramExporter.cs [hunk 4]
```diff
@@ -1,14 +1,11 @@
...
 using Newtonsoft.Json;
 
 namespace Yarn
 {
-    public class ProgramExporter
+    public static class ProgramExporter
     {
-        public ProgramExporter()
-        {
-        }
```
Comment (Tamschi) [inline YarnSpinnerConsole/ProgramExporter.cs]: This class is only ever used statically, so I removed the unused constructor too. There's a warning about this now.

File: YarnSpinnerTests/TestBase.cs [hunk 5]
```diff
@@ -39,9 +40,7 @@ public class TestBase
 
                 var testDataDirectory = path.Take(index).ToList();
 
-                var pathToTestData = string.Join(Path.DirectorySeparatorChar.ToString(), testDataDirectory.ToArray());
-
-                pathToTestData = Path.DirectorySeparatorChar + pathToTestData;
```
Comment (Tamschi) [inline YarnSpinnerTests/TestBase.cs]: The tests wouldn't run for me with this line. This may have broken something on not-Windows, but I'm currently in no position to test it.

**Comment by Tamschi** [comment]
Almost forgot to update `CONTRIBUTORS.md` since it's not mentioned in `CONTRIBUTING.md`.

Sorry about that force-push. I forgot to pull the typo fix first and had a merge commit in there. Now it's nice and linear.

**Comment by desplesda** [comment]
This is an excellent pull request. Thank you very much!
